.PHONY: all clean

include mof.mk
SCRIPTS = ../scripts
OUTFILE := b_$(MOF)_$(SUPERCELL)_labeled.pdb

all: $(OUTFILE)

$(OUTFILE): a_$(MOF)_1x1x1_refined_type.cif
	$(SCRIPTS)/cif2pdb_labeled.py -r 3 3 3 $< $@

clean:
	-@rm -f $(OUTFILE)
